apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejemplo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejemplo
  template:
    metadata:
      labels:
        app: ejemplo
    spec:
      containers:
        - name: ejemplo-container
          image: joaquinsangiorgio/static-website
          imagePullPolicy: Always
          ports:
            - containerPort: 80